package com.musornibak.pocketclaw.ui.theme

import androidx.compose.ui.graphics.Color

val PqBackground            = Color(0xFF0E0E0E)
val PqSurface               = Color(0xFF161616)
val PqSurfaceVariant        = Color(0xFF2A2A2A)
val PqSurfaceContainer      = Color(0xFF1F1F1F)
val PqSurfaceContainerHigh  = Color(0xFF2A2A2A)
val PqSurfaceContainerHighest = Color(0xFF333333)
val PqOutline               = Color(0xFF2F2F2F)
val PqOutlineVariant        = Color(0xFF3A3A3A)
val PqOnBackground          = Color(0xFFECECEC)
val PqOnSurface             = Color(0xFFECECEC)
val PqOnSurfaceVariant      = Color(0xFF9C9C9C)
val PqPrimary               = Color(0xFFECECEC)
val PqOnPrimary             = Color(0xFF0E0E0E)
val PqPrimaryContainer      = Color(0xFF2A2A2A)
val PqOnPrimaryContainer    = Color(0xFFECECEC)
val PqSecondary             = Color(0xFFB0B0B0)
val PqOnSecondary           = Color(0xFF0E0E0E)
val PqSecondaryContainer    = Color(0xFF1F1F1F)
val PqOnSecondaryContainer  = Color(0xFFECECEC)
val PqTertiary              = Color(0xFF8A8A8A)
val PqOnTertiary            = Color(0xFF0E0E0E)
val PqTertiaryContainer     = Color(0xFF1F1F1F)
val PqOnTertiaryContainer   = Color(0xFFECECEC)
val PqError                 = Color(0xFFCF6679)
val PqOnError               = Color(0xFF1A1A1A)
val PqErrorContainer        = Color(0xFF3A1A1F)
val PqOnErrorContainer      = Color(0xFFECECEC)

val PqLightBackground            = Color(0xFFF7F7F7)
val PqLightSurface               = Color(0xFFFFFFFF)
val PqLightSurfaceVariant        = Color(0xFFE5E5E5)
val PqLightSurfaceContainer      = Color(0xFFF0F0F0)
val PqLightSurfaceContainerHigh  = Color(0xFFE7E7E7)
val PqLightSurfaceContainerHighest = Color(0xFFDDDDDD)
val PqLightOutline               = Color(0xFFCCCCCC)
val PqLightOutlineVariant        = Color(0xFFD9D9D9)
val PqLightOnBackground          = Color(0xFF111111)
val PqLightOnSurface             = Color(0xFF111111)
val PqLightOnSurfaceVariant      = Color(0xFF555555)
val PqLightPrimary               = Color(0xFF111111)
val PqLightOnPrimary             = Color(0xFFFFFFFF)
val PqLightPrimaryContainer      = Color(0xFFE0E0E0)
val PqLightOnPrimaryContainer    = Color(0xFF111111)
val PqLightSecondary             = Color(0xFF444444)
val PqLightOnSecondary           = Color(0xFFFFFFFF)
val PqLightSecondaryContainer    = Color(0xFFE7E7E7)
val PqLightOnSecondaryContainer  = Color(0xFF111111)
val PqLightTertiary              = Color(0xFF666666)
val PqLightOnTertiary            = Color(0xFFFFFFFF)
val PqLightTertiaryContainer     = Color(0xFFEAEAEA)
val PqLightOnTertiaryContainer   = Color(0xFF111111)
